#!/usr/bin/env bash
set -e

nix --extra-experimental-features "nix-command flakes" build ".#darwinConfigurations.powerbook.system" $@

sudo ./result/sw/bin/darwin-rebuild switch --flake '.#powerbook'
